In [1]:
class10_Score= [["Ram", 76, "Meena", 87, "Deepak", 81, "Sahil", 36, "Aarti", 47]]

In [2]:
import numpy as np
class10_Score1= np.array(class10_Score)

In [3]:
class10_Score

[['Ram', 76, 'Meena', 87, 'Deepak', 81, 'Sahil', 36, 'Aarti', 47]]

In [27]:
type(class10_Score)

list

In [4]:
class10_Score1

array([['Ram', '76', 'Meena', '87', 'Deepak', '81', 'Sahil', '36',
        'Aarti', '47']], dtype='<U6')

In [26]:
type(class10_Score1)

numpy.ndarray

In [6]:
class10_Score.append("Surender")

In [7]:
class10_Score.append(70)

In [8]:
class10_Score

[['Ram', 76, 'Meena', 87, 'Deepak', 81, 'Sahil', 36, 'Aarti', 47],
 'Surender',
 70]

In [9]:
class10_Score1

array([['Ram', '76', 'Meena', '87', 'Deepak', '81', 'Sahil', '36',
        'Aarti', '47']], dtype='<U6')

In [10]:
np.delete(class10_Score1,-1)

array(['Ram', '76', 'Meena', '87', 'Deepak', '81', 'Sahil', '36', 'Aarti'],
      dtype='<U6')

In [12]:
class10_Score=[10,20,40]

In [13]:
class10_Score + class10_Score

[10, 20, 40, 10, 20, 40]

In [14]:
class10_score1= np.array([10,20,40])

In [15]:
class10_score1 + class10_score1

array([20, 40, 80])

In [16]:
class10_Score2= np.array([10,50,60,80,90,95,72])

In [17]:
class10_Score2 > 60

array([False, False, False,  True,  True,  True,  True])

In [18]:
class10_Score2[class10_Score2 > 60]

array([80, 90, 95, 72])

In [19]:
np_2d= np.array([[5,7,5,5,6],
                [6,8,9,8,4]])

In [20]:
np_2d

array([[5, 7, 5, 5, 6],
       [6, 8, 9, 8, 4]])

In [21]:
np_2d.shape

(2, 5)

In [22]:
np_2d[1,3]

8

In [23]:
np_2d[1][3]

8

In [24]:
np_2d[:,1:3]

array([[7, 5],
       [8, 9]])

In [25]:
np_2d[1,:]

array([6, 8, 9, 8, 4])